services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\DoctrineSensitiveTagBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  Tourze\DoctrineSensitiveTagBundle\Service\:
    resource: '../../Service/'
